# Site settings
title: std::gregwar
email: gregoire.hirt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I, Grégoire (std::gregwar), am a swiss programmer,
  currently learning computer science at EPFL.
  Devoted to OpenGL and all kind of graphical and audio
  applications, I'm very into eye candy, procedural
  generation and simulations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stdgregwar.github.io" # the base hostname & protocol for your site
github_username:  stdgregwar

# Build settings
markdown: kramdown
